- name: Download k8s repo key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.37/deb/Release.key
    dest: /tmp/k8s-release.key
    mode: "0644" 

- name: convert .key into gpg
  ansible.builtin.command:
    cmd: gpg --dearmor --yes --output /etc/apt/keyrings/k8s-apt-keyring.gpg /tmp/k8s-release.key
  args:
    creates: /etc/apt/keyrings/k8s-apt-keyring.gpg

- name: add k8s repo
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/k8s-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.37/deb/ / 
    filename: kubernetes
    state: present

- name: Install K8s packages
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true

- name: Block to update k8s packages
  ansible.builtin.dpkg_selections:
    name: '{{ item }}'
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: enable kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: true

- name: copy kubeadm-conf
  template:
    src: initconfig.j2
    dest: /home/{{ ansible_user }}/kubeadm-conf.yaml
    owner: "{{ ansible_user }}"
    mode: '0644'

- name: init k8s cluster
  command: kubeadm init --config /home/{{ ansible_user }}/kubeadm-conf.yaml --ignore-preflight-errors=NumCPU,Mem
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init
  changed_when: kubeadm_init.rc == 0

- name: Create .kube directory
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"

- name: copy k8s admin conf to home dir
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    mode: '0644'
    remote_src: true

- name: Change ownership of admin.conf
  file:
    path: /home/{{ ansible_user }}/.kube/config.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Install Flannel CNI
  command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  become: false
  changed_when: false

- name: get node name
  command: kubectl get nodes -o jsonpath='{.items[0].metadata.name}'
  register: node_name
  become: false
  changed_when: false

- name: Wait Ready status node
  command: kubectl get node {{ node_name.stdout }} -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}'
  register: node_ready
  until: node_ready.stdout == "True"
  retries: 10
  delay: 30
  become: false
  changed_when: false


## For Testing Stand

# Single Node
- name: Allow workloads on control-plane node
  ansible.builtin.command:
    cmd: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  become: false
  register: remove_taint
  failed_when:
    - remove_taint.rc != 0
    - "'not found' not in remove_taint.stderr"
  changed_when: remove_taint.rc == 0


# Kyverno
- name: helm add repo
  command:
    helm repo add kyverno https://kyverno.github.io/kyverno/
  become: false

- name: helm update repo
  command:
    helm repo update
  become: false

- name: helm install kyverno
  command:
    helm upgrade --install kyverno kyverno/kyverno -n kyverno --create-namespace
  become: false

- name: copy kyverno policy
  template:
    src: kyverno-policy.yaml
    dest: /home/{{ ansible_user }}/kyverno-policy.yaml

- name: deploy kyverno-policy
  command:
    kubectl apply -f /home/{{ ansible_user }}/kyverno-policy.yaml
  become: false


# MetalLB for external IP
- name: deploy metalLB
  command:
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.16.1/config/manifests/metallb-native.yaml
  become: false

- name: create contoller deployment
  command:
    kubectl -n metallb-system rollout status deployment/controller
  become: false

- name: create speaker daemonset
  command: 
    kubectl -n metallb-system rollout status daemonset/speaker
  become: false

- name: copy IPaddressPool
  template:
    src: ipaddressPool.j2
    dest: /home/{{ ansible_user }}/ipaddressPool.yaml
   
- name: deploy ipaddressPool
  command:
    kubectl apply -f /home/{{ ansible_user }}/ipaddressPool.yaml
  become: false



