- name: create directory for keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: download docker gpg keyrings
  command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  changed_when: false

- name: add docker repo to source
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker Packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: download cri-dockerd package
  get_url:
    url: "https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.15/cri-dockerd_0.3.15.3-0.ubuntu-jammy_amd64.deb"
    dest: /tmp/cri-dockerd.deb

- name: Install CRI-DOckerd package
  dpkg_selections:
    name: /tmp/cri-dockerd.deb
    selection: install


