--- 
- name: prepare k8s mode
  hosts: k8s
  become: true
  environment:
    KUBECONFIG="/home/{{ ansible_user }}/.kube/config.yaml"

  roles:
#    - common
    - kubernetes
    - nginx
#    - gateway
#    - prometheus
#    - logging
    - security
