- name: download helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: run helm script
  command: bash /tmp/get_helm.sh

# Kyverno
- name: helm add repo
  command:
    helm repo add kyverno https://kyverno.github.io/kyverno/
  become: false

- name: helm update repo
  command:
    helm repo update
  become: false

- name: helm install kyverno
  command:
    helm upgrade --install kyverno kyverno/kyverno -n kyverno --create-namespace
  become: false

- name: copy kyverno policy
  template:
    src: kyverno-policy.yaml
    dest: /home/{{ ansible_user }}/kyverno-policy.yaml

- name: deploy kyverno-policy
  command:
    kubectl apply -f /home/{{ ansible_user }}/kyverno-policy.yaml
  become: false

- name: install Envoy Gateway
  command:
    helm upgrade --install eg oci://docker.io/envoyproxy/gateway-helm --version v1.6.3 -n envoy-gateway-system --create-namespace
  become: false

- name: Copy GatewayClass
  template:
    src: gateway_class.yaml
    dest: /home/{{ ansible_user }}/gateway_class.yaml

- name: deploy GatewayClass
  command:
    kubectl apply -f /home/{{ ansible_user }}/gateway_class.yaml
  become: false

- name: copy Gateway Object
  template:
    src: gateway_object.yaml
    dest: /home/{{ ansible_user }}/gateway_object.yaml

- name: deploy Gateway Object
  command:
    kubectl apply -f /home/{{ ansible_user }}/gateway_object.yaml
  become: false

- name: copy HTTPRoute
  template:
    src: httproute.yaml
    dest: /home/{{ ansible_user }}/httproute.yaml

- name: deploy httproute
  command:
    kubectl apply -f /home/{{ ansible_user }}/httproute.yaml
  become: false


